apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-jenkins
spec:
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: cont1
          image: aktham3/flask
---
apiVersion: v1
kind: Service
metadata:
  name: flask/svc
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 31250
  selector:
    app: flask
